// Generated by CoffeeScript 1.4.0
(function() {

  define(["router/router"], function(Router) {
    var initialize;
    initialize = function() {
      return Router.initialize();
    };
    return {
      initialize: initialize
    };
  });

}).call(this);
