// Generated by CoffeeScript 1.4.0
(function() {

  require.config({
    baseUrl: "js",
    paths: {
      jquery: "libs/jquery.1.8.3-dev",
      underscore: "libs/underscore.1.4.3-dev",
      backbone: "libs/backbone.0.9.9-dev",
      "backbone.localStorage": "libs/backbone.localStorage.1.0.0-dev",
      text: "libs/require/text.2.0.3-dev",
      mustache: "libs/mustache.0.7.1-dev"
    },
    shim: {
      underscore: {
        exports: "_"
      },
      backbone: {
        deps: ["underscore", "jquery"],
        exports: "Backbone"
      },
      "backbone.localStorage": {
        deps: ["backbone"],
        exports: "Backbone"
      }
    }
  });

  require(["app"], function(app) {
    return app.initialize();
  });

}).call(this);
