// Generated by CoffeeScript 1.4.0

/*
Complete View of Survery
*/


(function() {

  define(["jquery", "backbone", "mustache", "text!../templates/completeTemplate.html"], function($, Backbone, Mustache, template) {
    var CompleteView;
    CompleteView = Backbone.View.extend({
      initialize: function() {
        return console.info("CompleteView: View initialized");
      },
      el: "#pageContent",
      template: Mustache.compile(template),
      render: function() {
        var compiledTemplate;
        console.log("Render: CompleteView");
        compiledTemplate = this.template({
          answers: JSON.stringify(this.answers, void 0, 2)
        });
        return this.$el.html(compiledTemplate);
      },
      setResults: function(answers) {
        return this.answers = answers;
      },
      answers: null
    });
    return CompleteView;
  });

}).call(this);
