// Generated by CoffeeScript 1.4.0

/*
Homepage View of Survey
*/


(function() {

  define(["jquery", "underscore", "backbone", "mustache", "text!../templates/homeTemplate.html"], function($, _, Backbone, Mustache, template) {
    var HomeView;
    HomeView = Backbone.View.extend({
      initialize: function() {
        return console.info("HomeView: View initialized");
      },
      el: "#pageContent",
      template: Mustache.compile(template),
      render: function() {
        var compiledTemplate;
        console.log("Render: HomeView");
        compiledTemplate = this.template({});
        return this.$el.html(compiledTemplate);
      }
    });
    return HomeView;
  });

}).call(this);
