// Generated by CoffeeScript 1.4.0

/*
Main Questions View

Display questions in order added to collection
*/


(function() {

  define(["jquery", "underscore", "backbone", "mustache", "../collections/questions", "../views/completeView", "text!../templates/questionTemplate.html"], function($, _, Backbone, Mustache, Questions, CompleteView, template) {
    var QuestionView;
    QuestionView = Backbone.View.extend({
      initialize: function() {
        console.info("QuestionView: View initialized");
        return this.questions = new Questions();
      },
      el: "#pageContent",
      template: Mustache.compile(template),
      _currentPosition: 0,
      render: function() {
        var compiledTemplate, question;
        console.log("Render: questionView");
        question = this.questions.at(this._currentPosition);
        compiledTemplate = this.template({
          questionNumber: parseInt(this._currentPosition) + 1,
          question: question.escape("text")
        });
        return this.$el.html(compiledTemplate);
      },
      events: {
        "click #trueButton": "handleTrue",
        "click #falseButton": "handleFalse"
      },
      handleTrue: function(evt) {
        return this.completeQuestion(true);
      },
      handleFalse: function(evt) {
        return this.completeQuestion(false);
      },
      completeQuestion: function(selected) {
        var completeView, question;
        question = this.questions.at(this._currentPosition);
        question.set("selected", selected);
        question.completed();
        if (++this._currentPosition < this.questions.length) {
          window.location.href = "#/question/" + this._currentPosition;
          return;
        }
        completeView = new CompleteView();
        completeView.setResults(this.questions.getAnswers());
        completeView.render();
        return window.location.href = "#/complete";
      },
      setCurrentPosition: function(currentPosition) {
        return this._currentPosition = currentPosition;
      }
    });
    return QuestionView;
  });

}).call(this);
