// Generated by CoffeeScript 1.4.0

/*
<**** NOT USED - Currently generated straight from questions Collection****>
*/


(function() {

  define(["backbone"], function(Backbone) {
    var Answer;
    Answer = new Backbone.Model.extend({
      initialize: function() {
        return console.info("Answer: Model initialized");
      },
      defaults: {
        selected: false
      }
    });
    return Answer;
  });

}).call(this);
