// Generated by CoffeeScript 1.4.0
(function() {

  define(["backbone"], function(Backbone) {
    var Question;
    Question = Backbone.Model.extend({
      initialize: function() {
        return console.info("Question: Model initialized");
      },
      defaults: {
        text: "",
        selected: false,
        completed: false
      },
      completed: function() {
        return this.save({
          completed: true
        });
      }
    });
    return Question;
  });

}).call(this);
